// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBST6aCaRn0A9yRSIzWiCwrIlQtcmqFs40',
    appId: '1:950693853680:android:66c51c372e32b9f1354535',
    messagingSenderId: '950693853680',
    projectId: 'mekfriend',
    databaseURL: 'https://mekfriend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mekfriend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ2XM052HzWp5LdQIOdx8ho_ur3ZuwbGU',
    appId: '1:950693853680:ios:9145807e95899e7c354535',
    messagingSenderId: '950693853680',
    projectId: 'mekfriend',
    databaseURL: 'https://mekfriend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mekfriend.appspot.com',
    iosClientId: '950693853680-m51f00caeipuhl18ecvnkeeerlkrmurb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );
}
